### ISSUE TITLE
Version 0.1.1 npm package doesn't contain the wdio-errorshot-reporter.js file

### ISSUE THREAD

**Issue by TheOptimist** [JulianVallee/wdio-errorshot-reporter#1]
I was going to try this package out but version 0.1.1 is unusable because the npm package doesn't contain the file that actually does the work. I get a fatal termination in my application because the reporter isn't installed.

**Comment by JulianVallee** [comment]
Thanks for reporting and sorry for the inconvenience! I will have a fix within the next hours.

**Comment by JulianVallee** [comment]
Alright, version 0.2.0 of the package is now released and includes a fix to make it work again.

You should also revisit the readme and take a quick look the configuration section though, there are some necessary changes due to a issue I haven't catched earlier in my local development setup.

Hope you can enjoy the package now!

**Comment by TheOptimist** [comment]
Thanks, seen the 0.2.0 package, but seems that I'm still drawing a blank. Installing via NPM and download the tarball still only include the package.json and the readme.

**Comment by JulianVallee** [comment]
I messed up with the .npmignore file, so I removed it altogether as I learned that npm has some sane default ignores on board.

I have also tested the 0.2.1 package in a completely fresh environment, and finally the issue should be solved.

Thanks for your feedback!

**Comment by TheOptimist** [comment]
That looks like it's done the trick. Will be putting into use tomorrow and making it a dev dependency. Thanks for providing this!

**Comment by JulianVallee** [comment]
Awesome, good to hear! I'll close the issue for now then.
